# Delete these routes and define your own shop routes here

acme_sylius_example_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: ForgeLabsUk\SyliusUnleashedOrdersPlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

acme_sylius_example_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: ForgeLabsUk\SyliusUnleashedOrdersPlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~

forge_labs_uk_sylius_unleashed_orders_plugin_order_controller:
    path: /api/orders
    controller: ForgeLabsUk\SyliusUnleashedOrdersPlugin\Controller\SyliusOrderToUnleashedController::SyliusOrdersToUnleashedAction
    methods: [GET, POST]
